/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package peter.ass;

import javax.swing.JOptionPane;

/**
 *
 * @author RR
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lab1 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        lab2 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        lab3 = new javax.swing.JLabel();
        lab4 = new javax.swing.JLabel();
        txt4 = new javax.swing.JTextField();
        lab5 = new javax.swing.JLabel();
        txt5 = new javax.swing.JTextField();
        lab6 = new javax.swing.JLabel();
        lab7 = new javax.swing.JLabel();
        lab8 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        bt3 = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        pw1 = new javax.swing.JPasswordField();
        pw2 = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(143, 170, 220));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        jLabel1.setText("SIGN UP");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 14, -1, -1));

        lab1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lab1.setText("First Name :");
        jPanel1.add(lab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 93, -1, -1));
        jPanel1.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 92, 374, 29));

        lab2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lab2.setText("Last Name :");
        jPanel1.add(lab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 128, -1, -1));
        jPanel1.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 127, 374, 29));

        lab3.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lab3.setText("Address :");
        jPanel1.add(lab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 177, -1, -1));

        lab4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lab4.setText("Email :");
        jPanel1.add(lab4, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 285, -1, -1));
        jPanel1.add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 280, 374, 29));

        lab5.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lab5.setText("P No :");
        jPanel1.add(lab5, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 322, -1, -1));
        jPanel1.add(txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 321, 374, 29));

        lab6.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lab6.setText("Password :");
        jPanel1.add(lab6, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 368, -1, -1));

        lab7.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lab7.setText("Re Type Password :");
        jPanel1.add(lab7, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 410, -1, -1));

        lab8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lab8.setText("Select :");
        jPanel1.add(lab8, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 464, -1, -1));

        bg1.add(rb1);
        rb1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rb1.setText("Customer");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });
        jPanel1.add(rb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, -1, -1));

        bg1.add(rb2);
        rb2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rb2.setText("Shop Manager");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });
        jPanel1.add(rb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, -1, -1));

        bg1.add(rb3);
        rb3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rb3.setText("Director");
        rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3ActionPerformed(evt);
            }
        });
        jPanel1.add(rb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 570, -1, -1));

        bt3.setBackground(new java.awt.Color(102, 204, 255));
        bt3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bt3.setText("HOME");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        jPanel1.add(bt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 631, 210, 70));

        bt1.setBackground(new java.awt.Color(102, 204, 255));
        bt1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bt1.setText("SIGN IN");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        jPanel1.add(bt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 630, 210, 70));

        bt2.setBackground(new java.awt.Color(102, 204, 255));
        bt2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bt2.setText("SIGN UP");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        jPanel1.add(bt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 630, 210, 70));
        jPanel1.add(pw1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 368, 374, 24));
        jPanel1.add(pw2, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 412, 374, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 168, 374, -1));

        jLabel7.setText("==================================================================================================================================================================================");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/peter small.png"))); // NOI18N
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 0, 65, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb2ActionPerformed

    private void rb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb3ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new main_int().setVisible(true);
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new login().setVisible(true);

        

    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new cu_int().setVisible(true);
        
        JOptionPane.showMessageDialog(this, "Sign Up Successful !");
    }//GEN-LAST:event_bt2ActionPerformed

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg1;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lab1;
    private javax.swing.JLabel lab2;
    private javax.swing.JLabel lab3;
    private javax.swing.JLabel lab4;
    private javax.swing.JLabel lab5;
    private javax.swing.JLabel lab6;
    private javax.swing.JLabel lab7;
    private javax.swing.JLabel lab8;
    private javax.swing.JPasswordField pw1;
    private javax.swing.JPasswordField pw2;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    // End of variables declaration//GEN-END:variables
}
